install_dependencies:
  script:
    - BASE_POINT=`curl --header "PRIVATE-TOKEN:$API_READ_TOKEN" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/pipelines?ref=${CI_COMMIT_BRANCH}&status=success&per_page=1" | jq -r '.[0] |.sha'`
    - echo $BASE_POINT
    - docker build -f base.Dockerfile -t $AWS_ECR_URL/ecr-repo:base-$CI_COMMIT_SHORT_SHA \
      --cache-from=type=registry,ref=$AWS_ECR_URL/ecr-repo:cache-base-$BASE_POINT \
      --cache-from=type=registry,ref=$AWS_ECR_URL/ecr-repo:cache-base-$CI_COMMIT_SHORT_SHA \
      --cache-to=type=registry,ref=$AWS_ECR_URL/ecr-repo:cache-base-$CI_COMMIT_SHORT_SHA,mode=max,image-manifest=true \
      --load --push .

build:
  script:
    - docker build -f services/build.Dockerfile -t $AWS_ECR_URL/ecr-repo:build-$CI_COMMIT_SHORT_SHA --push \
      --build-arg BASE_IMAGE=$AWS_ECR_URL/ecr-repo:base-$CI_COMMIT_SHORT_SHA \
      --build-arg service_folder=management \
      --target service-builder \
      --cache-from=type=registry,ref=$AWS_ECR_URL/ecr-repo:cache-base-$BASE_POINT  \
      --cache-from=type=registry,ref=$AWS_ECR_URL/ecr-repo:cache-base-$CI_COMMIT_SHORT_SHA \
      --cache-from=type=registry,ref=$AWS_ECR_URL/ecr-repo:cache-build-$BASE_POINT \
      --cache-from=type=registry,ref=$AWS_ECR_URL/ecr-repo:cache-build-$CI_COMMIT_SHORT_SHA \
      --cache-to=type=registry,ref=$AWS_ECR_URL/ecr-repo:cache-build-$CI_COMMIT_SHORT_SHA,mode=max,image-manifest=true \
      --load --push .

deploy:
  script:
   - docker run --rm --entrypoint="/bin/bash" user/app:build-stage yarn test